// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'1eac07cc9552de79f5c257fe9a46a49b1732b6dfa6b8d249a686067f8282457f'>;
export type ExecutionHash =
  ExecutionHashBase<'11aa8ab3c71beff5824df15fbd60aab6065621a0bff5b0ebeb7e1d1954ef52ea'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Application: {
      readonly decidedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly decisionEmailSentAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly eventId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly status: 'SUBMITTED' | 'ACCEPTED' | 'REJECTED';
      readonly submittedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly volunteerId: CodecTypes['pg/text@1']['output'];
    };
    readonly ApplicationAnswer: {
      readonly applicationId: CodecTypes['pg/text@1']['output'];
      readonly fieldId: CodecTypes['pg/text@1']['output'];
      readonly fileUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly textValue: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Event: {
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly coverImageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly endsAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly externalApplicationUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly location: CodecTypes['pg/text@1']['output'];
      readonly organizerId: CodecTypes['pg/text@1']['output'];
      readonly skillsWanted: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly slots: CodecTypes['pg/int4@1']['output'];
      readonly startsAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly status: 'DRAFT' | 'PUBLISHED' | 'CLOSED';
      readonly title: CodecTypes['pg/text@1']['output'];
    };
    readonly Form: {
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly eventId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
    };
    readonly FormField: {
      readonly formId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly label: CodecTypes['pg/text@1']['output'];
      readonly options: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly order: CodecTypes['pg/int4@1']['output'];
      readonly required: CodecTypes['pg/bool@1']['output'];
      readonly type: 'SHORT_TEXT' | 'LONG_TEXT' | 'SINGLE_CHOICE' | 'FILE';
    };
    readonly OrganizerProfile: {
      readonly contactEmail: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
    };
    readonly VolunteerProfile: {
      readonly age: CodecTypes['pg/int4@1']['output'] | null;
      readonly availability: CodecTypes['pg/text@1']['output'] | null;
      readonly bio: CodecTypes['pg/text@1']['output'] | null;
      readonly city: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly fullName: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly skills: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Application: {
      readonly decidedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly decisionEmailSentAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly eventId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly status: 'SUBMITTED' | 'ACCEPTED' | 'REJECTED';
      readonly submittedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly volunteerId: CodecTypes['pg/text@1']['input'];
    };
    readonly ApplicationAnswer: {
      readonly applicationId: CodecTypes['pg/text@1']['input'];
      readonly fieldId: CodecTypes['pg/text@1']['input'];
      readonly fileUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly textValue: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Event: {
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly coverImageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly endsAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly externalApplicationUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly location: CodecTypes['pg/text@1']['input'];
      readonly organizerId: CodecTypes['pg/text@1']['input'];
      readonly skillsWanted: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly slots: CodecTypes['pg/int4@1']['input'];
      readonly startsAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly status: 'DRAFT' | 'PUBLISHED' | 'CLOSED';
      readonly title: CodecTypes['pg/text@1']['input'];
    };
    readonly Form: {
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly eventId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
    };
    readonly FormField: {
      readonly formId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly label: CodecTypes['pg/text@1']['input'];
      readonly options: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly order: CodecTypes['pg/int4@1']['input'];
      readonly required: CodecTypes['pg/bool@1']['input'];
      readonly type: 'SHORT_TEXT' | 'LONG_TEXT' | 'SINGLE_CHOICE' | 'FILE';
    };
    readonly OrganizerProfile: {
      readonly contactEmail: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
    };
    readonly VolunteerProfile: {
      readonly age: CodecTypes['pg/int4@1']['input'] | null;
      readonly availability: CodecTypes['pg/text@1']['input'] | null;
      readonly bio: CodecTypes['pg/text@1']['input'] | null;
      readonly city: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly fullName: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly skills: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Application: {
      readonly decidedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly decisionEmailSentAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly eventId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly status: 'SUBMITTED' | 'ACCEPTED' | 'REJECTED';
      readonly submittedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly volunteerId: CodecTypes['pg/text@1']['output'];
    };
    readonly ApplicationAnswer: {
      readonly applicationId: CodecTypes['pg/text@1']['output'];
      readonly fieldId: CodecTypes['pg/text@1']['output'];
      readonly fileUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly textValue: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Event: {
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly coverImageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly endsAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly externalApplicationUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly location: CodecTypes['pg/text@1']['output'];
      readonly organizerId: CodecTypes['pg/text@1']['output'];
      readonly skillsWanted: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly slots: CodecTypes['pg/int4@1']['output'];
      readonly startsAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly status: 'DRAFT' | 'PUBLISHED' | 'CLOSED';
      readonly title: CodecTypes['pg/text@1']['output'];
    };
    readonly Form: {
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly eventId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
    };
    readonly FormField: {
      readonly formId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly label: CodecTypes['pg/text@1']['output'];
      readonly options: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly order: CodecTypes['pg/int4@1']['output'];
      readonly required: CodecTypes['pg/bool@1']['output'];
      readonly type: 'SHORT_TEXT' | 'LONG_TEXT' | 'SINGLE_CHOICE' | 'FILE';
    };
    readonly OrganizerProfile: {
      readonly contactEmail: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
    };
    readonly VolunteerProfile: {
      readonly age: CodecTypes['pg/int4@1']['output'] | null;
      readonly availability: CodecTypes['pg/text@1']['output'] | null;
      readonly bio: CodecTypes['pg/text@1']['output'] | null;
      readonly city: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly fullName: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly skills: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Application: {
      readonly decidedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly decisionEmailSentAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly eventId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly status: 'SUBMITTED' | 'ACCEPTED' | 'REJECTED';
      readonly submittedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly volunteerId: CodecTypes['pg/text@1']['input'];
    };
    readonly ApplicationAnswer: {
      readonly applicationId: CodecTypes['pg/text@1']['input'];
      readonly fieldId: CodecTypes['pg/text@1']['input'];
      readonly fileUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly textValue: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Event: {
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly coverImageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly endsAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly externalApplicationUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly location: CodecTypes['pg/text@1']['input'];
      readonly organizerId: CodecTypes['pg/text@1']['input'];
      readonly skillsWanted: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly slots: CodecTypes['pg/int4@1']['input'];
      readonly startsAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly status: 'DRAFT' | 'PUBLISHED' | 'CLOSED';
      readonly title: CodecTypes['pg/text@1']['input'];
    };
    readonly Form: {
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly eventId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
    };
    readonly FormField: {
      readonly formId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly label: CodecTypes['pg/text@1']['input'];
      readonly options: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly order: CodecTypes['pg/int4@1']['input'];
      readonly required: CodecTypes['pg/bool@1']['input'];
      readonly type: 'SHORT_TEXT' | 'LONG_TEXT' | 'SINGLE_CHOICE' | 'FILE';
    };
    readonly OrganizerProfile: {
      readonly contactEmail: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
    };
    readonly VolunteerProfile: {
      readonly age: CodecTypes['pg/int4@1']['input'] | null;
      readonly availability: CodecTypes['pg/text@1']['input'] | null;
      readonly bio: CodecTypes['pg/text@1']['input'] | null;
      readonly city: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly fullName: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly skills: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Application = {
    decidedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    decisionEmailSentAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    eventId: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    status: 'SUBMITTED' | 'ACCEPTED' | 'REJECTED';
    submittedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    volunteerId: CodecTypes['pg/text@1']['output'];
    answers: public_ApplicationAnswer[];
    event: public_Event;
    volunteer: public_User;
    readonly [RelationKeys]?: 'answers' | 'event' | 'volunteer';
  };
  export type public_ApplicationAnswer = {
    applicationId: CodecTypes['pg/text@1']['output'];
    fieldId: CodecTypes['pg/text@1']['output'];
    fileUrl: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/text@1']['output'];
    textValue: CodecTypes['pg/text@1']['output'] | null;
    application: public_Application;
    field: public_FormField;
    readonly [RelationKeys]?: 'application' | 'field';
  };
  export type public_Event = {
    city: CodecTypes['pg/text@1']['output'];
    coverImageUrl: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    description: CodecTypes['pg/text@1']['output'];
    endsAt: CodecTypes['pg/timestamptz-string@1']['output'];
    externalApplicationUrl: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/text@1']['output'];
    location: CodecTypes['pg/text@1']['output'];
    organizerId: CodecTypes['pg/text@1']['output'];
    skillsWanted: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
    slots: CodecTypes['pg/int4@1']['output'];
    startsAt: CodecTypes['pg/timestamptz-string@1']['output'];
    status: 'DRAFT' | 'PUBLISHED' | 'CLOSED';
    title: CodecTypes['pg/text@1']['output'];
    applications: public_Application[];
    form: public_Form | null;
    organizer: public_User;
    readonly [RelationKeys]?: 'applications' | 'form' | 'organizer';
  };
  export type public_Form = {
    description: CodecTypes['pg/text@1']['output'] | null;
    eventId: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    title: CodecTypes['pg/text@1']['output'];
    event: public_Event;
    fields: public_FormField[];
    readonly [RelationKeys]?: 'event' | 'fields';
  };
  export type public_FormField = {
    formId: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    label: CodecTypes['pg/text@1']['output'];
    options: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
    order: CodecTypes['pg/int4@1']['output'];
    required: CodecTypes['pg/bool@1']['output'];
    type: 'SHORT_TEXT' | 'LONG_TEXT' | 'SINGLE_CHOICE' | 'FILE';
    answers: public_ApplicationAnswer[];
    form: public_Form;
    readonly [RelationKeys]?: 'answers' | 'form';
  };
  export type public_OrganizerProfile = {
    contactEmail: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    description: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    userId: CodecTypes['pg/text@1']['output'];
    user: public_User;
    readonly [RelationKeys]?: 'user';
  };
  export type public_User = {
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    applications: public_Application[];
    events: public_Event[];
    organizerProfile: public_OrganizerProfile | null;
    volunteerProfile: public_VolunteerProfile | null;
    readonly [RelationKeys]?: 'applications' | 'events' | 'organizerProfile' | 'volunteerProfile';
  };
  export type public_VolunteerProfile = {
    age: CodecTypes['pg/int4@1']['output'] | null;
    availability: CodecTypes['pg/text@1']['output'] | null;
    bio: CodecTypes['pg/text@1']['output'] | null;
    city: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    fullName: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    skills: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
    userId: CodecTypes['pg/text@1']['output'];
    user: public_User;
    readonly [RelationKeys]?: 'user';
  };
}

export declare const models: {
  public: {
    Application: Models.public_Application;
    ApplicationAnswer: Models.public_ApplicationAnswer;
    Event: Models.public_Event;
    Form: Models.public_Form;
    FormField: Models.public_FormField;
    OrganizerProfile: Models.public_OrganizerProfile;
    User: Models.public_User;
    VolunteerProfile: Models.public_VolunteerProfile;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly Application: {
              columns: {
                readonly decidedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly decisionEmailSentAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly eventId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly submittedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly volunteerId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['eventId', 'volunteerId'] }];
              indexes: readonly [
                {
                  readonly name: 'Application_eventId_idx_6a266d47';
                  readonly prefix: 'Application_eventId_idx';
                  readonly columns: readonly ['eventId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Application_volunteerId_idx_b41cb3e4';
                  readonly prefix: 'Application_volunteerId_idx';
                  readonly columns: readonly ['volunteerId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Application';
                    readonly columns: readonly ['eventId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Event';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Application';
                    readonly columns: readonly ['volunteerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly ApplicationAnswer: {
              columns: {
                readonly applicationId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly fieldId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly fileUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly textValue: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'ApplicationAnswer_applicationId_idx_8158f91a';
                  readonly prefix: 'ApplicationAnswer_applicationId_idx';
                  readonly columns: readonly ['applicationId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'ApplicationAnswer_fieldId_idx_44d815d7';
                  readonly prefix: 'ApplicationAnswer_fieldId_idx';
                  readonly columns: readonly ['fieldId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'ApplicationAnswer';
                    readonly columns: readonly ['applicationId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Application';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'ApplicationAnswer';
                    readonly columns: readonly ['fieldId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'FormField';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Event: {
              columns: {
                readonly city: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly coverImageUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly endsAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly externalApplicationUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly location: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly organizerId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly skillsWanted: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly slots: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly startsAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Event_city_idx_40fed80d';
                  readonly prefix: 'Event_city_idx';
                  readonly columns: readonly ['city'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Event_organizerId_idx_17a44ca9';
                  readonly prefix: 'Event_organizerId_idx';
                  readonly columns: readonly ['organizerId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Event_status_idx_e98638ab';
                  readonly prefix: 'Event_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Event';
                    readonly columns: readonly ['organizerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Form: {
              columns: {
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly eventId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['eventId'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Form';
                    readonly columns: readonly ['eventId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Event';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly FormField: {
              columns: {
                readonly formId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly label: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly options: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly order: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly required: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'FormField_formId_idx_3c13a9fa';
                  readonly prefix: 'FormField_formId_idx';
                  readonly columns: readonly ['formId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'FormField';
                    readonly columns: readonly ['formId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Form';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly OrganizerProfile: {
              columns: {
                readonly contactEmail: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['userId'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'OrganizerProfile';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly User: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly VolunteerProfile: {
              columns: {
                readonly age: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly availability: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly bio: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly city: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly fullName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly skills: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['userId'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'VolunteerProfile';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly ApplicationStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['SUBMITTED', 'ACCEPTED', 'REJECTED'];
            };
            readonly EventStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['DRAFT', 'PUBLISHED', 'CLOSED'];
            };
            readonly FormFieldType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['SHORT_TEXT', 'LONG_TEXT', 'SINGLE_CHOICE', 'FILE'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Application: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Application';
    };
    readonly ApplicationAnswer: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ApplicationAnswer';
    };
    readonly Event: { readonly namespace: 'public' & NamespaceId; readonly model: 'Event' };
    readonly Form: { readonly namespace: 'public' & NamespaceId; readonly model: 'Form' };
    readonly FormField: { readonly namespace: 'public' & NamespaceId; readonly model: 'FormField' };
    readonly OrganizerProfile: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'OrganizerProfile';
    };
    readonly User: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly VolunteerProfile: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'VolunteerProfile';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Application: {
            readonly fields: {
              readonly decidedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly decisionEmailSentAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly eventId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly submittedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly volunteerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly answers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ApplicationAnswer';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['applicationId'];
                };
              };
              readonly event: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Event';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['eventId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly volunteer: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['volunteerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Application';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly decidedAt: { readonly column: 'decidedAt' };
                readonly decisionEmailSentAt: { readonly column: 'decisionEmailSentAt' };
                readonly eventId: { readonly column: 'eventId' };
                readonly id: { readonly column: 'id' };
                readonly status: { readonly column: 'status' };
                readonly submittedAt: { readonly column: 'submittedAt' };
                readonly volunteerId: { readonly column: 'volunteerId' };
              };
            };
          };
          readonly ApplicationAnswer: {
            readonly fields: {
              readonly applicationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fieldId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fileUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly textValue: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly application: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Application';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['applicationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly field: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'FormField';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['fieldId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'ApplicationAnswer';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly applicationId: { readonly column: 'applicationId' };
                readonly fieldId: { readonly column: 'fieldId' };
                readonly fileUrl: { readonly column: 'fileUrl' };
                readonly id: { readonly column: 'id' };
                readonly textValue: { readonly column: 'textValue' };
              };
            };
          };
          readonly Event: {
            readonly fields: {
              readonly city: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly coverImageUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly endsAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly externalApplicationUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly location: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly organizerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly skillsWanted: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly slots: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly startsAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly applications: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Application';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['eventId'];
                };
              };
              readonly form: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Form' };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['eventId'];
                };
              };
              readonly organizer: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['organizerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Event';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly city: { readonly column: 'city' };
                readonly coverImageUrl: { readonly column: 'coverImageUrl' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly description: { readonly column: 'description' };
                readonly endsAt: { readonly column: 'endsAt' };
                readonly externalApplicationUrl: { readonly column: 'externalApplicationUrl' };
                readonly id: { readonly column: 'id' };
                readonly location: { readonly column: 'location' };
                readonly organizerId: { readonly column: 'organizerId' };
                readonly skillsWanted: { readonly column: 'skillsWanted' };
                readonly slots: { readonly column: 'slots' };
                readonly startsAt: { readonly column: 'startsAt' };
                readonly status: { readonly column: 'status' };
                readonly title: { readonly column: 'title' };
              };
            };
          };
          readonly Form: {
            readonly fields: {
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly eventId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly event: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Event';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['eventId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly fields: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'FormField';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['formId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Form';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly description: { readonly column: 'description' };
                readonly eventId: { readonly column: 'eventId' };
                readonly id: { readonly column: 'id' };
                readonly title: { readonly column: 'title' };
              };
            };
          };
          readonly FormField: {
            readonly fields: {
              readonly formId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly label: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly options: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly order: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly required: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly answers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ApplicationAnswer';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['fieldId'];
                };
              };
              readonly form: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Form' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['formId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'FormField';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly formId: { readonly column: 'formId' };
                readonly id: { readonly column: 'id' };
                readonly label: { readonly column: 'label' };
                readonly options: { readonly column: 'options' };
                readonly order: { readonly column: 'order' };
                readonly required: { readonly column: 'required' };
                readonly type: { readonly column: 'type' };
              };
            };
          };
          readonly OrganizerProfile: {
            readonly fields: {
              readonly contactEmail: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'OrganizerProfile';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly contactEmail: { readonly column: 'contactEmail' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly description: { readonly column: 'description' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly userId: { readonly column: 'userId' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly applications: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Application';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['volunteerId'];
                };
              };
              readonly events: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Event';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['organizerId'];
                };
              };
              readonly organizerProfile: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'OrganizerProfile';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly volunteerProfile: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'VolunteerProfile';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'User';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly email: { readonly column: 'email' };
                readonly id: { readonly column: 'id' };
              };
            };
          };
          readonly VolunteerProfile: {
            readonly fields: {
              readonly age: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly availability: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly bio: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly city: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly fullName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly skills: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'VolunteerProfile';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly age: { readonly column: 'age' };
                readonly availability: { readonly column: 'availability' };
                readonly bio: { readonly column: 'bio' };
                readonly city: { readonly column: 'city' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly fullName: { readonly column: 'fullName' };
                readonly id: { readonly column: 'id' };
                readonly skills: { readonly column: 'skills' };
                readonly userId: { readonly column: 'userId' };
              };
            };
          };
        };
        readonly enum: {
          readonly ApplicationStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'SUBMITTED'; readonly value: 'SUBMITTED' },
              { readonly name: 'ACCEPTED'; readonly value: 'ACCEPTED' },
              { readonly name: 'REJECTED'; readonly value: 'REJECTED' },
            ];
          };
          readonly EventStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'DRAFT'; readonly value: 'DRAFT' },
              { readonly name: 'PUBLISHED'; readonly value: 'PUBLISHED' },
              { readonly name: 'CLOSED'; readonly value: 'CLOSED' },
            ];
          };
          readonly FormFieldType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'SHORT_TEXT'; readonly value: 'SHORT_TEXT' },
              { readonly name: 'LONG_TEXT'; readonly value: 'LONG_TEXT' },
              { readonly name: 'SINGLE_CHOICE'; readonly value: 'SINGLE_CHOICE' },
              { readonly name: 'FILE'; readonly value: 'FILE' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'Application';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'ApplicationAnswer';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'Event';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'Form';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'FormField';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'OrganizerProfile';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'User';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'VolunteerProfile';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
